%
% This program runs saliency detection for each video file in the list
%
%% Specify lists for input and output files
iList={...
    '../out/beverly03.mpg', ...
    '../out/gamecube02.mpg', ...
    '../out/gamecube04.mpg', ...
    '../out/gamecube05.mpg', ...
    '../out/gamecube18.mpg'
     %'..\\..\\data\\saliencyDataCrcns\\tv-action01.mpg', ...
     %'..\\..\\data\\saliencyDataCrcns\\tv-talk01.mpg' ...
    };
oList={...
    '../out/beverly03_saliency.mpg', ...
    '../out/gamecube02_saliency.mpg', ...
    '../out/gamecube04_saliency.mpg', ...
    '../out/gamecube05_saliency.mpg', ...
    '../out/gamecube18_saliency.mpg'
%'..\\..\\data\\saliencyResultsCrcns\\beverly05_saliency.avi', ...
    % '..\\..\\data\\saliencyResultsCrcns\\tv-action01_saliency.avi', ...
    % '..\\..\\data\\saliencyResultsCrcns\\tv-talk01_saliency.avi' ...
    };
oMList={...
    '../out/beverly03_saliency.mat', ...
    '../out/gamecube02_saliency.mat', ...
    '../out/gamecube04_saliency.mat', ...
    '../out/gamecube05_saliency.mat', ...
    '../out/gamecube18_saliency.mat'
    %'..\\..\\data\\saliencyResultsCrcns\\beverly05_saliency.mat', ...
    % '..\\..\\data\\saliencyResultsCrcns\\tv-action01_saliency.mat', ...
    % '..\\..\\data\\saliencyResultsCrcns\\tv-talk01_saliency.mat' ...
    };

%% Perform saliency detection for each file
wsize_s=3; wsize_t=3; wsize_fs=5; wsize_ft=5; 
scaleFactor=1/8; segLength=100;
for k=1:length(iList)
    iFName=iList{k};
    fprintf('%s\n',iFName);
    oFName=oList{k};
    oMFName=oMList{k};
    detSal(iFName,oFName,oMFName,wsize_s,wsize_t,...
        wsize_fs,wsize_ft,scaleFactor,segLength);
end

fprintf('Done\n');
%% End of program